### ISSUE TITLE
Transcription For Q&A: Is there a known issue with friend's games not showing cross-platform?

### ISSUE THREAD

**Issue by sean-abercrombie** [Satisfactory-Clips-Archive/video-clip-notes#7]
# https://www.youtube.com/watch?v=y5z4GmkeGhA

# Topics
Multiplayer

# Transcription
Snutt: Tier 17!
Jace: Uh is there a known issue with friends' games not showing cross-platform?
Jace: My epic [mumbling] store keeps not seeing games hosted by Steam friends.
Jace: There is one possibility there.
Jace: And that is the selection at the beginning when you started the game when all this happened.
Jace: Whether or not you ena.. uh allowed [Snutt clears throat] uh what like Epic and Steam to link. 
Jace: And I think that makes a difference.
Jace: Um if one of you, either your or your friend has done it.
Snutt (overlapping): Yes, so it's
Jace: Like not linked.
Snutt: (overlapping): Exactly
Jace: Then that can close that issue.
Jace: If you both did link them then I don't know.
Snutt: Yeah cause it's like your your your friends on the Steam version needs to link their Epic account for them to show up in the Epic version.
Snutt: Albeit there are some case where like you... no one shows up in the list. 
Snutt: I've seen sometimes when I've played. 
Snutt: Uh sometimes just like restarting the game uh gets it working again. 
Snutt: But yeah, it's it's like we're working on those type of things uh to see if we can flush them out.
Snutt: It's possible that it gets better in the EOS update we're pushing this week. 
Snutt: Uh one can hope. 
Snutt: Uh... but we'll keep looking into those types of issues in the future.

**Comment by SignpostMarv** [comment]
linking to #5

**Comment by SignpostMarv** [comment]
currently being processed by youtube

**Comment by SignpostMarv** [comment]
done, thank you :D
