### ISSUE TITLE
Transcription for Q&A: Add a Tape Measure or something to gauge distance between two objects?

### ISSUE THREAD

**Issue by sean-abercrombie** [Satisfactory-Clips-Archive/video-clip-notes#8]
# Video URL
https://www.youtube.com/watch?v=-hFvijwVlSQ

# Topics
User interface
Pipes
Pumps
New topic proposal: suggestions/questions website plug

# Transcription
Snutt: Good one!
Jace: Add a tape measure?!
Jace: Something to gauge distance between two objects.
Snutt: mmmh
Jace: Hmm Interesting, I've never heard that before.
Snutt: Y'know what that's actually when when so so I was doing pipes or pumps the other day.
Snutt: And like pumps only work for like what is it twenty meters? Ten meters?
Snutt: Something like that.
Snutt: That's when you would actually have use for that.
Snutt: Cause you want to measure on the pipe like how far up is that?
Jace: Yeah yeah that could be good.
Snutt: Yeah
Jace: And I mean just for planning I guess it could be good.
Snutt: Yeah
Jace: Catch you later aligator thanks for your reviews.
Snutt: Yeah
Snutt: Ten out Ten reviews from aligator on this stream.
Jace: Yeah
Jace: Plus two for nut
Snutt: No! Minus two for no nut.. or.. yeah
Jace: Plus four for not [unintellible]
Jace: Um maybe showing meters away on pings
Jace: Yeah could be interesting.
Jace: So Sooo the whole measuring and pings stuff let's uh let's uh
Snutt: Oh look at that. Plug our questions
Jace: We have a website.
Jace: questions.satisfactorygame.com
Jace: It is the best place to make suggestions or ask any questions or report bugs.
Jace: Uhm so I think this is a great thing to add over there
Jace: For sure
Snutt: Yes
Jace: Cause like we can't remember every single suggestion and then like run to a producer and be like "Do this" and then he runs to a programmer and is like "Do this"
Jace: Uh y'know so it's like on the website it's good cause it stays there.
Jace: And we do check it.
Snutt: Yeah yeah they have enough shit to do uuuh in their planning.
Snutt: So we can't really disrupt too much.
Jace: Yep
Snutt: So unless it's on the questions website they can't plan for it so to speak.

**Comment by SignpostMarv** [comment]
topic changes mostly done, not sure about adding a topic for the suggestions website 🤔

**Comment by SignpostMarv** [comment]
awaiting youtube processing

**Comment by SignpostMarv** [comment]
done, thanks :D
